name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build --parallel
    - name: Run docker services
      run: docker-compose up -d
    - name: Wait for services to be up
      run: timeout 30 bash -c 'while ! curl -fSsL localhost:8000; do sleep 1; done'
    - name: Run tests
      run: docker-compose exec -T cypress bash /app/run_tests.sh
